name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build
        run: ./gradlew build

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/libs/*.jar
